model: hf 

model_args: 
  pretrained: meta-llama/Llama-3.1-8B-Instruct 
  dtype: bfloat16

apply_chat_template : True 

log_samples: True

output_path: ./results/ 

device: cuda:0 

batch_size: 4

# do_sample does greedy decoding if True
gen_kwargs:
  temperature: 0.7
  top_p: 0.9
  do_sample: True
  until:
  - "</s>"