model: hf 

model_args: 
  pretrained: mistralai/Ministral-3-14B-Instruct-2512

apply_chat_template : True 

log_samples: True

output_path: ./results/ 

device: cuda:0 

batch_size: "auto"

# do_sample does greedy decoding if True
gen_kwargs:
  max_gen_toks: 2048
  temperature: 0.7
  do_sample: false
  until:
  - "</s>"